args:
- auto: PREDEFINED
  description: The XSOAR Training playbook to execute
  name: playbook
  predefined:
  - Sub-Playbook Inputs & Outputs - AD User Lookup
  - Loops - For Each
  - Loops - Builtin
  - Loops - Loop on Array Data
  - Extend Context - Set By Incident
  - Extend Context - AD Get User
  - Lists - Internal IP
  - Lists - Environment
  - SLA Timer Breach
  - Data Collection Tasks
  - Set Grid Field
  required: true
comment: 'This automation sets the playbook on a given Incident based on a list of
  options.  '
commonfields:
  id: XSOARTrainingPlaybookButton
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dockerimage: demisto/python3:3.10.10.48392
enabled: true
engineinfo: {}
mainengineinfo: {}
name: XSOARTrainingPlaybookButton
pswd: ""
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('XSOARTrainingPlaybookButton', 'start', __line__())


  # This automation sets the playbook on a given Incident based on a list of options in the playbook argument.

  PLAYBOOK_MAP = {
      "Sub-Playbook Inputs & Outputs - AD User Lookup": "XSOAR Engineer Training - AD User Lookup (Parent)",
      "Loops - For Each": "XSOAR Engineer Training - For Each Loops (Parent)",
      "Loops - Builtin": "XSOAR Engineer Training - Builtin Loops (Parent)",
      "Loops - Loop on Array Data": "XSOAR Engineer Training - Loop on Array Data",
      "Extend Context - Set By Incident": "XSOAR Engineer Training - Extend Context - Set By Incident",
      "Extend Context - AD Get User": "XSOAR Engineer Training - Extend Context - AD Get User",
      "Lists - Internal IP": "XSOAR Engineer Training - Lists - Internal IPs",
      "Lists - Environment": "XSOAR Engineer Training - Lists - Environment List",
      "SLA Timer Breach": "XSOAR Engineer Training - SLA Timer Breach Example",
      "Data Collection Tasks": "XSOAR Engineer Training - Data Collection Tasks",
      "Set Grid Field": "XSOAR Engineer Training - Set Grid Field"
  }

  # get the argument for the playbook
  playbook = demisto.args().get("playbook")
  playbook = PLAYBOOK_MAP.get(playbook, "None")

  # set new playbook
  demisto.results(demisto.executeCommand("setPlaybook", {"name": playbook}))

  register_module_line('XSOARTrainingPlaybookButton', 'end', __line__())
scripttarget: 0
subtype: python3
system: true
tags:
- incident-action-button
- xet
type: python
