commonfields:
  id: fe54362d-6c24-49cd-8071-9d12cd6d2461
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dockerimage: demisto/python3:3.10.12.63474
enabled: true
engineinfo: {}
mainengineinfo: {}
name: SetPlaybook_InstallPackage
pswd: ""
runas: DBotWeakRole
runonce: false
script: |-
  incident = demisto.incidents()[0]
  incidentId = incident['id']

  demisto.executeCommand('setPlaybook', {'incidentId':incidentId,'name':'FortiManager - Install Policy Package on Device'})
scripttarget: 0
subtype: python3
tags:
- Firewall Changes
- AC
- incident-action-button
type: python
