contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1ce04f1e-a284-42f4-8c5e-c65267b477fb
inputs: []
name: FAZ - Extract indicator from events
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 267c32ad-5ba4-4d7e-8847-81a9e8535256
      iscommand: false
      name: ""
      version: -1
    taskid: 267c32ad-5ba4-4d7e-8847-81a9e8535256
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    reputationcalc: 2
    scriptarguments:
      text:
        simple: ${events}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Extract all indicators according to server indicators configuration
      id: 38bc3aad-9e23-4a6d-8cd6-7c6e7c86cb09
      iscommand: true
      name: extractIndicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 38bc3aad-9e23-4a6d-8cd6-7c6e7c86cb09
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: '${ExtractedIndicators} '
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f2f4e0ec-609c-4a55-8145-28036dbf0f04
      iscommand: true
      name: Set Field
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: f2f4e0ec-609c-4a55-8145-28036dbf0f04
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${events}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${events}
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6556925a-cadd-4dc6-81a6-539a424368fe
      iscommand: false
      name: Check Events
      type: condition
      version: -1
    taskid: 6556925a-cadd-4dc6-81a6-539a424368fe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: The events were not fetched or the list is empty
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 21d26704-3a0c-4fc2-87cd-ead2723de301
      iscommand: true
      name: Set Field
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 21d26704-3a0c-4fc2-87cd-ead2723de301
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 8e67cee6-2dc2-40ef-816a-046be0524018
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 8e67cee6-2dc2-40ef-816a-046be0524018
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Address
          root: IP
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      tags:
        simple: FAZ
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of multiple indicators
      id: 4a4eb423-a4f8-46eb-87f2-ec5d031f612f
      iscommand: true
      name: setIndicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: 4a4eb423-a4f8-46eb-87f2-ec5d031f612f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Data
          root: URL
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      tags:
        simple: FAZ
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of multiple indicators
      id: 517666eb-7673-4799-8b65-ed1ffd0d5958
      iscommand: true
      name: setIndicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: 517666eb-7673-4799-8b65-ed1ffd0d5958
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
