contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook demonstrates using the values in an XSOAR list in a playbook.  Specifically
  a list called environment that holds which environment we are dealing with!
id: XSOAR Engineer Training - Lists - Environment List
inputs: []
name: XSOAR Engineer Training - Lists - Environment List
outputs: []
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4e7d6aa7-0fb7-4de6-8269-73744003fd40
      iscommand: false
      name: ""
      version: -1
    taskid: 4e7d6aa7-0fb7-4de6-8269-73744003fd40
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: lists.environment
          operator: isEqualString
          right:
            value:
              simple: development
      label: development
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: lists.environment
          operator: isEqualString
          right:
            value:
              simple: test
      label: test
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: lists.environment
          operator: isEqualString
          right:
            value:
              simple: production
      label: production
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      development:
      - "2"
      production:
      - "4"
      test:
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check which environment we have in the list.
      id: e299cf30-3239-4f4f-8ee1-bb17f56c672e
      iscommand: false
      name: 'Check Environment '
      type: condition
      version: -1
    taskid: e299cf30-3239-4f4f-8ee1-bb17f56c672e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: DEVELOPMENT!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: ef342a9c-280a-4187-8226-4130c1d90190
      iscommand: false
      name: Print Development Environment
      script: Print
      type: regular
      version: -1
    taskid: ef342a9c-280a-4187-8226-4130c1d90190
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: TEST!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 3e518810-8ad0-4d3e-873d-e4592d76b350
      iscommand: false
      name: Print Test Environment
      script: Print
      type: regular
      version: -1
    taskid: 3e518810-8ad0-4d3e-873d-e4592d76b350
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: PRODUCTION!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: f15b509a-bbf0-4d74-84be-8679415812be
      iscommand: false
      name: Print Production Environment
      script: Print
      type: regular
      version: -1
    taskid: f15b509a-bbf0-4d74-84be-8679415812be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2fbe4ae0-806e-4caa-8b18-53b1b6c26b3e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2fbe4ae0-806e-4caa-8b18-53b1b6c26b3e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          ## XSOAR Engineer Training - Lists - Environment List

          This playbook demonstrates using the values in an XSOAR list in a playbook.  Specifically a list called environment that holds which environment we are dealing with!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 342007d5-f0a0-49d0-8a83-d465c668fd35
      iscommand: false
      name: Print Playbook Overview
      script: Print
      type: regular
      version: -1
    taskid: 342007d5-f0a0-49d0-8a83-d465c668fd35
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 195
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: environment
          root: lists
          transformers:
          - operator: toUpperCase
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8f523809-b7d4-4281-82a7-c85e972caf5b
      iscommand: false
      name: Print Other Environment in Upper Case
      script: Print
      type: regular
      version: -1
    taskid: 8f523809-b7d4-4281-82a7-c85e972caf5b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: lists.environment
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              simple: lists.environment
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the list exists.
      id: 8d1174b8-b82d-4410-8983-41a84046e9c0
      iscommand: false
      name: Does the Environment list exist?
      type: condition
      version: -1
    taskid: 8d1174b8-b82d-4410-8983-41a84046e9c0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: You need to create the environment list in XSOAR, do this by navigating
          to Settings -> Advanced -> Lists
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 21969555-5216-4eca-81a2-8c6d7b886252
      iscommand: false
      name: Print instructions for creating the Environment list
      script: Print
      type: regular
      version: -1
    taskid: 21969555-5216-4eca-81a2-8c6d7b886252
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1740,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 2070,
        "x": 50,
        "y": 50
      }
    }
  }
