contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This sub-playbook will check to see if the user exists in AD based on
  the inputed email address.\n\nIf the user exists, it will add the user to a key
  called Exists, if not add them to NotExists.  \n\nThese keys are outputs of this
  sub-playbook which will be returned to the parent."
id: XSOAR Engineer Training - AD User Lookup (Sub-Playbook)
inputs:
- description: Array of users email addresses to lookup
  key: Users
  playbookInputQuery: null
  required: true
  value: {}
name: XSOAR Engineer Training - AD User Lookup (Sub-Playbook)
outputs:
- contextPath: Exists
  description: List of users who exist
  type: unknown
- contextPath: NotExisted
  description: List of users who don't exist
  type: unknown
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 98b74cd2-5096-4c5b-8d86-f89af8a93fc0
      iscommand: false
      name: ""
      version: -1
    taskid: 98b74cd2-5096-4c5b-8d86-f89af8a93fc0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        complex:
          root: inputs.Users
    separatecontext: false
    skipunavailable: false
    task:
      brand: XSOAR Engineer Training
      description: Retrieves detailed information about a user account. The user can
        be specified by username, email address, or as an Active Directory Distinguished
        Name (DN).
      id: b3810009-4db6-4aef-8dae-76ccc3d3b805
      iscommand: true
      name: ad-get-user
      script: XSOAR Engineer Training|||ad-get-user
      type: regular
      version: -1
    taskid: b3810009-4db6-4aef-8dae-76ccc3d3b805
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: mail
                root: ActiveDirectory.Users
          operator: isExists
          right:
            value: {}
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: ActiveDirectory.Users.mail
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: inputs.Users
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the user exists.
      id: 505456a0-dbcb-439a-8eb6-a24fbd679131
      iscommand: false
      name: Does User Exist?
      type: condition
      version: -1
    taskid: 505456a0-dbcb-439a-8eb6-a24fbd679131
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Exists
      value:
        complex:
          accessor: mail
          root: ActiveDirectory.Users
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 30af5bd2-0190-4097-8a2f-e1fc95970109
      iscommand: false
      name: Set Exists Key
      script: Set
      type: regular
      version: -1
    taskid: 30af5bd2-0190-4097-8a2f-e1fc95970109
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: NotExisted
      value:
        simple: ${inputs.Users}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: a4ac6b17-3f66-40ef-8183-f88d4860614c
      iscommand: false
      name: Set NotExisted Key
      script: Set
      type: regular
      version: -1
    taskid: a4ac6b17-3f66-40ef-8183-f88d4860614c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 71e4ddc9-6285-41a3-8a73-4ceb3e88ffb9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 71e4ddc9-6285-41a3-8a73-4ceb3e88ffb9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: dfc8f80e-a59e-4e41-826c-75b43fa6d9f8
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: dfc8f80e-a59e-4e41-826c-75b43fa6d9f8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: User
      value:
        simple: ${inputs.Users}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: be7b5187-abe9-43d1-878a-cdcd7fce784d
      iscommand: false
      name: Set User
      script: Set
      type: regular
      version: -1
    taskid: be7b5187-abe9-43d1-878a-cdcd7fce784d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
