contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 1.7.2
    packID: RecordedFuture
    packName: Recorded Future Intelligence
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Template playbook showing suggested steps to triage leaked credential
  alerts. Classifier/Mapper are available to ingest Recorded Future Leaked Credential
  Alerts.
id: Recorded Future Leaked Credential Alert Handling
inputs:
- description: ""
  key: account
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: name
      root: incident.recordedfuturealertentities
name: Recorded Future Leaked Credential Alert Handling
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9bb8e2cb-f516-4211-8d30-c68e96e56cba
      iscommand: false
      name: ""
      version: -1
    taskid: 9bb8e2cb-f516-4211-8d30-c68e96e56cba
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Username:
        simple: ${inputs.account}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich accounts using one or more integrations.
        Supported integrations:
        - Active Directory
        - SailPoint IdentityNow
        - SailPoint IdentityIQ
        - PingOne
        - Okta
        - AWS IAM

        Also, the playbook supports the generic command 'iam-get-user' (implemented in IAM integrations. For more information, visit https://xsoar.pan.dev/docs/integrations/iam-integrations.
      id: 6ef8e5c6-a6d8-40cc-8a47-0e015574bcbe
      iscommand: false
      name: Account Enrichment - Generic v2.1
      playbookId: Account Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: 6ef8e5c6-a6d8-40cc-8a47-0e015574bcbe
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "11"
      "YES":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0446baef-f96d-4e57-8313-86a7da5e6932
      iscommand: false
      name: Is the user account active?
      type: condition
      version: -1
    taskid: 0446baef-f96d-4e57-8313-86a7da5e6932
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 058b225b-c150-4fe1-82d5-72745147fcb7
      iscommand: false
      name: Query SIEM for suspicious behavior, logins, and location
      type: regular
      version: -1
    taskid: 058b225b-c150-4fe1-82d5-72745147fcb7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 530
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bcfa60cc-c41f-4231-8177-2d595fa78433
      iscommand: false
      name: Notify user
      type: regular
      version: -1
    taskid: bcfa60cc-c41f-4231-8177-2d595fa78433
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 705
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a85bd591-178b-4e15-8dac-2cac53771955
      iscommand: false
      name: Expire password
      type: regular
      version: -1
    taskid: a85bd591-178b-4e15-8dac-2cac53771955
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1250
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "YES":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6bf1fb31-b094-4970-843e-734b9be9c39c
      iscommand: false
      name: Verify activity
      type: condition
      version: -1
    taskid: 6bf1fb31-b094-4970-843e-734b9be9c39c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 875
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 59020c1c-d3ba-498a-817f-6198431031e7
      iscommand: false
      name: |
        Disable account
      type: regular
      version: -1
    taskid: 59020c1c-d3ba-498a-817f-6198431031e7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1090
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55b731a0-a7f4-4574-829b-dbe9f501747d
      iscommand: false
      name: Enable account
      type: regular
      version: -1
    taskid: 55b731a0-a7f4-4574-829b-dbe9f501747d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1420
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1a60c3f7-e6a5-49ae-8d1c-37ff545bc7bc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1a60c3f7-e6a5-49ae-8d1c-37ff545bc7bc
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 360,
          "y": 1680
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "2_11_#default#": 0.54,
      "8_11_YES": 0.13
    },
    "paper": {
      "dimensions": {
        "height": 1695,
        "width": 900,
        "x": 360,
        "y": 50
      }
    }
  }
