contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 1.7.2
    packID: RecordedFuture
    packName: Recorded Future Intelligence
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Template playbook showing suggested steps to triage new critical vulnerability
  alerts. Playbook include New and Critical CVEs. Classifier/Mapper are available
  to ingest Recorded Future New, Critical or Pre NVD Vulnerability Alerts.
id: Recorded Future Vulnerability Alert Handling
inputs:
- description: ""
  key: cve
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: name
      root: incident.recordedfuturealertentities
name: Recorded Future Vulnerability Alert Handling
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5fe7d07b-9e8e-422c-813a-4a20149202db
      iscommand: false
      name: ""
      version: -1
    taskid: 5fe7d07b-9e8e-422c-813a-4a20149202db
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      entity:
        simple: ${inputs.cve}
      entity_type:
        simple: cve
      fetch_related_entities:
        simple: "no"
      fetch_riskyCIDRips:
        simple: "no"
      profile:
        simple: Vulnerability Analyst
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get threat intelligence for an IP, Domain, CVE, URL or File.
      id: a2f08a83-3bad-4fe1-82aa-9a2c4f5304c1
      iscommand: true
      name: Enrich CVE Data
      script: '|||recordedfuture-intelligence'
      type: regular
      version: -1
    taskid: a2f08a83-3bad-4fe1-82aa-9a2c4f5304c1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      entity:
        simple: ${inputs.cve}
      entity_type:
        simple: cve
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get Insikt Group Research Links for an IP, Domain, CVE, URL or
        File.
      id: 1b680656-02c3-493a-8a22-1d356469039f
      iscommand: true
      name: Recorded Future Technical Links
      script: Recorded Future v2|||recordedfuture-links
      type: regular
      version: -1
    taskid: 1b680656-02c3-493a-8a22-1d356469039f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d9156b0f-e045-4e29-8870-b4a1c60f7065
      iscommand: false
      name: Compare CVE list with internal vuln data
      type: regular
      version: -1
    taskid: d9156b0f-e045-4e29-8870-b4a1c60f7065
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5abd364f-b167-4684-8541-7b69eb57d853
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5abd364f-b167-4684-8541-7b69eb57d853
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 725
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 740,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
