contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.7.2
    packID: RecordedFuture
    packName: Recorded Future Intelligence
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Threat Assessment using the Recorded Future SOAR Triage API and the context
  Phishing.
id: Recorded Future Threat Assessment
inputs:
- description: CVE ID to check if it is related to the C2 context.
  key: CVE
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: ID
      root: CVE
      transformers:
      - operator: uniq
- description: IP Address to check if it is related to the C2 context.
  key: IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      root: IP
      transformers:
      - operator: uniq
- description: URL to check if it is related to the C2 context.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
      transformers:
      - operator: uniq
- description: MD5 to check if it is related to the C2 context.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: SHA-1 to check if it is related to the C2 context.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
- description: SHA-256 to check if it is related to the C2 context.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: Domain to check if it is related to the C2 context.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Name
      root: Domain
      transformers:
      - operator: uniq
- description: Context to use for assessment. This is used by Recorded Future to calculate
    the relevant score and verdict. Valid values are "c2", "malware" and "phishing".
  key: threat-assessment-context
  playbookInputQuery: null
  required: true
  value:
    simple: phishing
- description: 'Makes sure that we filter out values that are zero in score from the
    threat assessment api. '
  key: filter
  playbookInputQuery: null
  required: false
  value:
    simple: "yes"
name: Recorded Future Threat Assessment
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.SHA256
  description: SHA-256
  type: string
- contextPath: File.SHA512
  description: SHA-512
  type: string
- contextPath: File.SHA1
  description: SHA-1
  type: string
- contextPath: File.MD5
  description: MD5
  type: string
- contextPath: File.CRC32
  description: CRC32
  type: string
- contextPath: File.CTPH
  description: CTPH
  type: string
- contextPath: IP.Address
  description: IP address
  type: string
- contextPath: IP.ASN
  description: ASN
  type: string
- contextPath: IP.Geo.Country
  description: IP Geolocation Country
  type: string
- contextPath: Domain.Name
  description: Domain name
  type: string
- contextPath: URL.Data
  description: URL name
  type: string
- contextPath: CVE.ID
  description: Vulnerability name
  type: string
- contextPath: RecordedFuture.verdict
  description: Recorded Future verdict
  type: boolean
- contextPath: RecordedFuture.context
  description: Threat Assessment Context
  type: string
- contextPath: RecordedFuture.riskScore
  description: Recorded Future Max Score
  type: number
- contextPath: RecordedFuture.Entities.id
  description: Entity ID
  type: string
- contextPath: RecordedFuture.Entities.name
  description: Entity Name
  type: string
- contextPath: RecordedFuture.Entities.type
  description: Entity Type
  type: string
- contextPath: RecordedFuture.Entities.score
  description: Entity Score
  type: string
- contextPath: RecordedFuture.Entities.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.Entities.Evidence.timestamp
  description: Recorded Future Evidence Timestamp
  type: date
- contextPath: RecordedFuture.Entities.Evidence.mitigation
  description: Recorded Future Evidence Mitigation
  type: string
- contextPath: RecordedFuture.Entities.Evidence.description
  description: Recorded Future Evidence Description
  type: string
- contextPath: RecordedFuture.Entities.Evidence.rule
  description: Recorded Future Risk Rule
  type: string
- contextPath: RecordedFuture.Entities.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: adb7954a-1b6a-4644-8985-ad77bdbc0295
      iscommand: false
      name: ""
      version: -1
    taskid: adb7954a-1b6a-4644-8985-ad77bdbc0295
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.CVE
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.IP
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.MD5
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.SHA1
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.SHA256
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the playbook's input contains at least one domain
        name to enrich.
      id: d70bec20-aa9b-44c2-8901-a8b730247d25
      iscommand: false
      name: Is there anything to assess?
      type: condition
      version: -1
    taskid: d70bec20-aa9b-44c2-8901-a8b730247d25
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d1410bed-68ef-4308-8a99-964df74ff88e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d1410bed-68ef-4308-8a99-964df74ff88e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 0,
          "y": 1100
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future v2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: 8b5c54f4-ef8e-4b2f-8af7-6bc093b49ff3
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 8b5c54f4-ef8e-4b2f-8af7-6bc093b49ff3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      context:
        simple: ${inputs.threat-assessment-context}
      cve:
        simple: ${inputs.CVE}
      domain:
        simple: ${inputs.Domain}
      file:
        simple: ${inputs.MD5},${inputs.SHA1},${inputs.SHA256}
      filter:
        simple: ${inputs.filter}
      ip:
        simple: ${inputs.IP}
      url:
        simple: ${inputs.URL}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get an indication of the risk based on context.
      id: 436a7665-15ab-4274-80fe-e9d17d0896e9
      iscommand: true
      name: Get Threat Assessment from Recorded Future
      script: Recorded Future v2|||recordedfuture-threat-assessment
      type: regular
      version: -1
    taskid: 436a7665-15ab-4274-80fe-e9d17d0896e9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 820
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 53365659-56c0-4f05-8e96-4437c06fcc74
      iscommand: false
      name: Threat Assessment Using Recorded Future API
      type: title
      version: -1
    taskid: 53365659-56c0-4f05-8e96-4437c06fcc74
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      recordedfuturethreatassessment:
        simple: ${RecordedFuture.Entities.context}
      value:
        simple: ${RecordedFuture.Entities.name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of an indicator
      id: 80d37316-6d8f-4e04-8993-39d4432ca5ee
      iscommand: true
      name: setIndicator
      script: Builtin|||setIndicator
      type: regular
      version: -1
    taskid: 80d37316-6d8f-4e04-8993-39d4432ca5ee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 980
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 790,
        "x": 0,
        "y": 50
      }
    }
  }
