contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: 'This playbook demos the BYOI OpenWeatherMap integration, as part of
  the XSOAR Training Pack. '
id: XSOAR Engineer Training - BYOI Take a Half Day
inputs: []
name: XSOAR Engineer Training - BYOI Take a Half Day
outputs: []
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e914c110-9f64-4fa3-8bd0-0c536e7b10f3
      iscommand: false
      name: ""
      version: -1
    taskid: e914c110-9f64-4fa3-8bd0-0c536e7b10f3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      city:
        complex:
          accessor: "0"
          root: Half Day.Answers
    separatecontext: false
    skipunavailable: false
    task:
      brand: OpenWeatherMap
      description: Retrieves the weather by provided city (where you wish you were)
      id: 5c379af6-0277-4779-80e3-426a00b8fcba
      iscommand: true
      name: Get the current Weather for ${Half Day.Answers.0}
      script: OpenWeatherMap|||openweather-by-city
      type: regular
      version: -1
    taskid: 5c379af6-0277-4779-80e3-426a00b8fcba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: OpenWeather.CurrentWeather.High
          operator: lessThan
          right:
            value:
              simple: "75"
      - - left:
            iscontext: true
            value:
              simple: OpenWeather.CurrentWeather.Low
          operator: greaterThanOrEqual
          right:
            value:
              simple: "20"
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 8840aae8-0122-4a7b-85ac-472b2ac9d082
      iscommand: false
      name: Is Today a Good Day to Half Day?
      type: condition
      version: -1
    taskid: 8840aae8-0122-4a7b-85ac-472b2ac9d082
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "3":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Half Day!!
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: true
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      value:
        simple: '# HALF DAY!'
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV2
      description: Prints text to war room (Markdown supported)
      id: ba4a34fa-8a82-40c3-8d8f-e074c7f1ebe4
      iscommand: false
      name: Notify Ori - Half day is on the menu!
      script: Print
      type: regular
      version: -1
    taskid: ba4a34fa-8a82-40c3-8d8f-e074c7f1ebe4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: b62a681e-aa2b-4867-8bad-65c0e6fe6424
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b62a681e-aa2b-4867-8bad-65c0e6fe6424
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "6"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      brandname:
        simple: OpenWeatherMap
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 86cf0666-2475-43bd-83c6-07f38d630d24
      iscommand: false
      name: Is the Open Weather integration available?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 86cf0666-2475-43bd-83c6-07f38d630d24
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    form:
      description: To half day or not to half day, is it even a question?
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: City
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: City
        type: shortText
      sender: ""
      title: Half Day
      totalanswers: 0
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Please enter the city you want to check the weather for.
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prompt for the city.
      id: d52b552a-9d46-4d3a-8568-d11ed200786a
      iscommand: false
      name: What city do you want to check the weather for?
      type: collection
      version: -1
    taskid: d52b552a-9d46-4d3a-8568-d11ed200786a
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        You need to configure an instance of the OpenWeatherMap integration to run this playbook.

        Configure the integration, and complete this task to continue.
      id: a799b55a-8867-4b53-8c89-daffd7ba2d3d
      iscommand: false
      name: Configure the OpenWeatherMap Integration
      type: regular
      version: -1
    taskid: a799b55a-8867-4b53-8c89-daffd7ba2d3d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 550
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: a4654a55-4d9d-4cad-8299-72f70ceb4f67
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: a4654a55-4d9d-4cad-8299-72f70ceb4f67
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: true
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      value:
        simple: 'Today is not a good day to half day.  But do what you need to do. '
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV2
      description: Prints text to war room (Markdown supported)
      id: 30ffa68b-6c32-4d70-8ad5-4d5ebcb433b6
      iscommand: false
      name: 'Weather sub-optimal, not the best day for a half day. '
      script: Print
      type: regular
      version: -1
    taskid: 30ffa68b-6c32-4d70-8ad5-4d5ebcb433b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 840,
        "x": 20,
        "y": 50
      }
    }
  }
