contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "Example Playbook which queries for Status from one incident, and then
  does a set by incident on it if it's not closed.   The use case is to update the
  original open Incident with additional information (such as another reporting user
  for a phishing email), so we can keep track, and deduplicate.\n\nEach step in the
  playbook may have some additional details in the details tab to explain what we
  are doing. "
id: XSOAR Engineer Training - Extend Context - Set By Incident
inputs: []
name: XSOAR Engineer Training - Extend Context - Set By Incident
outputs: []
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6f121cee-1322-4abc-85d6-5030e573a4d7
      iscommand: false
      name: ""
      version: -1
    taskid: 6f121cee-1322-4abc-85d6-5030e573a4d7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": -120
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: Enter the Incident number to query
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: What Incident?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Incident number
        type: number
      sender: ""
      title: Incident
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: What Incident should we query?
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Data collection task, to grab the Incident we want to query for
        status.
      id: a7a18bf8-06d4-4744-8fa2-260d11233407
      iscommand: false
      name: What Incident should we query?
      type: collection
      version: -1
    taskid: a7a18bf8-06d4-4744-8fa2-260d11233407
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: OtherIncidentStatus=Contents.data.status
      id:
        complex:
          accessor: "0"
          root: Incident.Answers
          transformers:
          - operator: Stringify
      ignore-outputs:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "For this we will use the search incidents automation to get the
        details of the other Incident.   \n\nhttps://xsoar.pan.dev/docs/reference/scripts/search-incidents-v2\n\nWe
        then use extend-context to put the Status of the other Incident into a context
        key to make it easier for us to use.   This can be used to put custom fields
        into context as well where the path would be Content.data.CustomFields.customfieldmachinename.\n\nhttps://xsoar.pan.dev/docs/playbooks/playbooks-extend-context#extending-context\n\nYou
        can use the argument raw-response=true on the CLI to see where we grab item
        for extend context."
      id: 087b54ef-7f64-46fc-8c97-9267f98449b8
      iscommand: false
      name: Search Incidents - Put the Status in Context using extend context (SEE
        DETAILS TAB FOR INFO)
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 087b54ef-7f64-46fc-8c97-9267f98449b8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 555
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: OtherIncidentStatus
                transformers:
                - args:
                    index:
                      value:
                        simple: "0"
                  operator: atIndex
          operator: isEqualNumber
          right:
            value:
              simple: "2"
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the other Incident is closed, based on the key we put
        into Context.
      id: 94d5c85e-1032-4059-8441-c14541ec2432
      iscommand: false
      name: Is the other Incident Closed?
      type: condition
      version: -1
    taskid: 94d5c85e-1032-4059-8441-c14541ec2432
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 'Other Incident Status: ${OtherIncident.status}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Prints text to war room (Markdown supported)
      id: af4f6833-0656-41c0-825a-a614c6584c4f
      iscommand: false
      name: Yes - Other Incident is Closed
      script: Print
      type: regular
      version: -1
    taskid: af4f6833-0656-41c0-825a-a614c6584c4f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      id:
        complex:
          accessor: "0"
          root: Incident.Answers
      key:
        simple: PersonWhoAnswered
      value:
        complex:
          accessor: name
          root: Incident.Answers
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Works the same as the 'Set' command, but can work across incidents by specifying 'id' as an argument. Sets a value into the context with the given context key. Doesn't append by default.

        Mike - For this we'll take the person who answered and add them to a key in context of the other open Incident before closing this one.  This could be adapted to send the reporter of an email for example to the other open Incident, closing the duplicate submission.  Then when the first Incident is closed, you just adapt the task that notifies the reporters about the type of email they submitted.
      id: 56f26763-ed88-4946-8f7b-7da403d86b2f
      iscommand: false
      name: Use SetByIncident to update the other Incident with the person who answered
        the question
      script: SetByIncidentId
      type: regular
      version: -1
    taskid: 56f26763-ed88-4946-8f7b-7da403d86b2f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context, used so we can re-run the playbook for
        developing them..
      id: e57186ab-00ff-4854-8389-51587b7b3cb6
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: e57186ab-00ff-4854-8389-51587b7b3cb6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 15
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b4215f0-b97b-42e4-87fe-a6fa8974e148
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0b4215f0-b97b-42e4-87fe-a6fa8974e148
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: "## XSOAR Engineer Training - Extend Context - Set By Incident\n\nExample
          Playbook which queries for Status from one incident, and then does a set
          by incident on it if it's not closed.   The use case is to update the original
          open Incident with additional information (such as another reporting user
          for a phishing email), so we can keep track, and deduplicate.\n\nEach step
          in the playbook may have some additional details in the details tab to explain
          what we are doing. "
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8616e502-f971-422f-8d63-92cf245063be
      iscommand: false
      name: Print Playbook Overview
      script: Print
      type: regular
      version: -1
    taskid: 8616e502-f971-422f-8d63-92cf245063be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1255,
        "width": 810,
        "x": 50,
        "y": -120
      }
    }
  }
