contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.7.2
    packID: RecordedFuture
    packName: Recorded Future Intelligence
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: File reputation using Recorded Future SOAR enrichment
id: Recorded Future File Reputation
inputs:
- description: MD5 hash for which to get the reputation.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: SHA-256 hash for which to get the reputation.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: SHA-1 hash for which to get reputation.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
name: Recorded Future File Reputation
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.SHA256
  description: File SHA-256
  type: string
- contextPath: File.SHA512
  description: File SHA-512
  type: string
- contextPath: File.SHA1
  description: File SHA-1
  type: string
- contextPath: File.MD5
  description: File MD5
  type: string
- contextPath: File.CRC32
  description: File CRC32
  type: string
- contextPath: File.CTPH
  description: File CTPH
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason that the vendor made the decision
  type: string
- contextPath: RecordedFuture.File.riskScore
  description: Recorded Future Hash Risk Score
  type: number
- contextPath: RecordedFuture.File.riskLevel
  description: Recorded Future Hash Risk Level
  type: string
- contextPath: RecordedFuture.File.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.File.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.File.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.File.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.File.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.File.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.File.name
  description: Hash
  type: string
- contextPath: RecordedFuture.File.maxRules
  description: Maximum count of Recorded Future Hash Risk Rules
  type: number
- contextPath: RecordedFuture.File.ruleCount
  description: Number of triggered Recorded Future Hash Risk Rules
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 74181337-dde0-4a67-8cb3-947f1e5b475c
      iscommand: false
      name: ""
      version: -1
    taskid: 74181337-dde0-4a67-8cb3-947f1e5b475c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 500,
          "y": -200
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
      - "15"
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 736504e0-6cc2-4ea8-8ba5-c12192af0bc2
      iscommand: false
      name: Get reputation using Recorded Future API
      type: title
      version: -1
    taskid: 736504e0-6cc2-4ea8-8ba5-c12192af0bc2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 195
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.MD5
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a file.
      id: 35a895eb-d8ec-4fd6-8b25-eb7f23b7da9e
      iscommand: true
      name: Get MD5 reputation
      script: Recorded Future v2|||file
      type: regular
      version: -1
    taskid: 35a895eb-d8ec-4fd6-8b25-eb7f23b7da9e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 665
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0cb4b168-d43a-426e-85f4-63341287ee88
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0cb4b168-d43a-426e-85f4-63341287ee88
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1370,
          "y": 1050
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.MD5
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.MD5}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is an MD5 hash in context.
      id: 58bb05e5-2b1d-4971-83e5-90ac5d7518de
      iscommand: false
      name: Is there an MD5 hash?
      type: condition
      version: -1
    taskid: 58bb05e5-2b1d-4971-83e5-90ac5d7518de
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA-256 hash in context.
      id: b870b692-b1a9-47f2-8852-c68c345aff51
      iscommand: false
      name: Is there a SHA-256 hash?
      type: condition
      version: -1
    taskid: b870b692-b1a9-47f2-8852-c68c345aff51
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 340
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.SHA256
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a file.
      id: fad9cc52-fc61-4eb3-80c4-70a4af1ac54c
      iscommand: true
      name: Get SHA-256 reputation
      script: Recorded Future v2|||file
      type: regular
      version: -1
    taskid: fad9cc52-fc61-4eb3-80c4-70a4af1ac54c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 665
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA1
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA-1 hash in context.
      id: b4368d5a-c045-407b-8cfb-aab08cebdfac
      iscommand: false
      name: Is there a SHA-1 hash?
      type: condition
      version: -1
    taskid: b4368d5a-c045-407b-8cfb-aab08cebdfac
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 340
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.SHA1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a file.
      id: eb590faf-6a42-4447-8f10-f09b45b979a7
      iscommand: true
      name: Get SHA-1 reputation
      script: Recorded Future v2|||file
      type: regular
      version: -1
    taskid: eb590faf-6a42-4447-8f10-f09b45b979a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 962.5,
          "y": 665
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future v2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: 4783ab5f-c69d-4c75-8188-72fb800630a1
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 4783ab5f-c69d-4c75-8188-72fb800630a1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": -70
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      recordedfutureriskrules:
        simple: ${RecordedFuture.File.rules}
      value:
        simple: ${RecordedFuture.File.name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of an indicator
      id: 97caa79f-8b3d-4565-86ae-2b0027ae5e8f
      iscommand: true
      name: setIndicator
      script: Builtin|||setIndicator
      type: regular
      version: -1
    taskid: 97caa79f-8b3d-4565-86ae-2b0027ae5e8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 855
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "14_7_#default#": 0.52,
      "15_7_#default#": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 1315,
        "width": 1700,
        "x": 50,
        "y": -200
      }
    }
  }
