contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4f6c5596-836c-49ed-86f6-f1ed5f395564
inputs: []
name: User Communication
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9a770731-ec30-4630-8e0a-2bf5b3321055
      iscommand: false
      name: ""
      version: -1
    taskid: 9a770731-ec30-4630-8e0a-2bf5b3321055
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: Please find the short description
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: This is a question for the customer
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: This is the help message
        type: singleSelect
      sender: ""
      title: This is the Web Survey Title
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Wait for the answer
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Test Email
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: alexandru.caracostea@gmail.com
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Microsoft Graph Mail Single User_instance_2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6bd7d04d-9263-4300-8061-f8d8bfcbfbc0
      iscommand: false
      name: User Communication
      type: collection
      version: -1
    taskid: 6bd7d04d-9263-4300-8061-f8d8bfcbfbc0
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: Playbook Finished
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Hello World Script
      id: 6f6ce96c-54a5-4b7d-877c-fdc5a6d47a4d
      iscommand: false
      name: Untitled Task
      script: HelloWorldScript
      type: regular
      version: -1
    taskid: 6f6ce96c-54a5-4b7d-877c-fdc5a6d47a4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 440
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 485,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
