contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8b4dfd8f-1664-4a18-8361-b169860b1612
inputs: []
name: Telia Link MS Defender Alerts to Incidents
outputs: []
quiet: true
starttaskid: "0"
tags:
- MS Defender
- AC
- Telia
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 69f20b21-d672-4034-8674-6a403fd39485
      iscommand: false
      name: ""
      version: -1
    taskid: 69f20b21-d672-4034-8674-6a403fd39485
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 56d3b1ae-daf0-4254-80a1-abf3b8cd8351
      iscommand: false
      name: Link alerts to incident
      script: 87b11aaf-10ed-4da6-807e-4a12a4032b66
      type: regular
      version: -1
    taskid: 56d3b1ae-daf0-4254-80a1-abf3b8cd8351
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Microsoft 365 Defender_instance_1
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ac10e3ae-d1fe-4817-89f0-9e7db78a36bf
      iscommand: false
      name: MSDefenderIncidentUpdate
      script: 77f1035a-6ca0-4cb3-8351-1480e0ff47e3
      type: regular
      version: -1
    taskid: ac10e3ae-d1fe-4817-89f0-9e7db78a36bf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
