contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This playbook demonstrates how to do sub-playbook looping using the
  Builtin method.  Basically looping over the embedded sub-playbook until results
  are returned (or not). \n"
id: XSOAR Engineer Training - Builtin Loops (Parent)
inputs: []
name: XSOAR Engineer Training - Builtin Loops (Parent)
outputs: []
starttaskid: "0"
system: true
tags:
- training
- xet
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bab9a809-a2db-4752-827d-56e06594697a
      iscommand: false
      name: ""
      version: -1
    taskid: bab9a809-a2db-4752-827d-56e06594697a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 1715a206-a52e-4b55-8f02-d31c157610c8
      iscommand: false
      name: 'Delete Context '
      script: DeleteContext
      type: regular
      version: -1
    taskid: 1715a206-a52e-4b55-8f02-d31c157610c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "We are going to loop using our sub-playbook, checking to see if
        we have results from splunk, and if not we back off and wait and then run
        again.  The loop will exit when there are results returned OR 5 loops have
        run. \n\nNote the loop setup, where we want to loop 5 times until data is
        returned.  However if the condition is not satisfied the playbook will error.
        \ We handle this by looping 6 times, and setting the condition on the 5th
        loop if no results are returned.  This means on the 6th loop, the condition
        will be checked at the beginning and our loop will exit gracefully. \n\n"
      id: 86188cc9-66c6-4475-8ba8-2c037acdae49
      iscommand: false
      name: Pause to explain
      type: regular
      version: -1
    taskid: 86188cc9-66c6-4475-8ba8-2c037acdae49
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              simple: SIEM.Result
          operator: isNotEmpty
          right:
            value: {}
      exitCondition: ""
      iscommand: false
      max: 6
      wait: 2
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: 'laptop=crossiscoming* '
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This sub-playbook runs a SIEM search, and also increments a counter
        to track how many loops were performed while waiting for a search result.  Used
        with the parent playbook to demonstrate the Builtin looping method.
      id: 88677e37-7976-4c76-8961-4b0d4bc1baeb
      iscommand: false
      name: XSOAR Engineer Training - Builtin Loops (Sub-Playbook)
      playbookId: XSOAR Engineer Training - Builtin Loops (Sub-Playbook)
      type: playbook
      version: -1
    taskid: 88677e37-7976-4c76-8961-4b0d4bc1baeb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 730
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SIEM.Result
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              simple: SIEM.Result
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: SIEM.Result
          operator: notContainsGeneral
          right:
            value:
              simple: NO RESULTS
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there was a result.
      id: 31333517-973c-4dad-8c62-fdafcde2db2c
      iscommand: false
      name: Was there a SIEM Result?
      type: condition
      version: -1
    taskid: 31333517-973c-4dad-8c62-fdafcde2db2c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: LoopCounter
          transformers:
          - operator: LastArrayElement
          - operator: Stringify
          - args:
              prefix:
                value:
                  simple: 'Results returned after '
              suffix:
                value:
                  simple: ' loops'
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 299ac90e-b9d6-400c-8feb-e1cdfc21f4ce
      iscommand: false
      name: SIEM search successful!
      script: Print
      type: regular
      version: -1
    taskid: 299ac90e-b9d6-400c-8feb-e1cdfc21f4ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2d8389ed-5dab-4846-8c1f-811f6d1ef50b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2d8389ed-5dab-4846-8c1f-811f6d1ef50b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: LoopCounter
          transformers:
          - operator: LastArrayElement
          - operator: Stringify
          - args:
              prefix:
                value:
                  simple: 'No results returned after '
              suffix:
                value:
                  simple: ' loops'
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a7b5ae0e-a6c9-4d42-8caf-4deb91c490ed
      iscommand: false
      name: SIEM search did not return results
      script: Print
      type: regular
      version: -1
    taskid: a7b5ae0e-a6c9-4d42-8caf-4deb91c490ed
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: "## XSOAR Engineer Training - Builtin Loops (Parent)\n\nThis playbook
          demonstrates how to do sub-playbook looping using the Builtin method.  Basically
          looping over the embedded sub-playbook until results are returned (or not).
          \n\nNote the setup, where we want to loop 5 times until data is returned.
          \ However if the condition is not satisfied the playbook will error.  We
          handle this by looping 6 times, and setting the condition on the 5th loop
          if no results are returned.  This means on the 6th loop, the condition will
          be checked at the beginning and our loop will exit gracefully. \n"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: bdf620eb-a92c-4603-88d3-1935facaa2d4
      iscommand: false
      name: Print Playbook Overview
      script: Print
      type: regular
      version: -1
    taskid: bdf620eb-a92c-4603-88d3-1935facaa2d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
