contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: 'This playbook demonstrates a for each loop with a sub-playbook to send
  each user an individual email. '
id: XSOAR Engineer Training - For Each Loops - Send Mail Example (Parent)
inputs: []
name: XSOAR Engineer Training - For Each Loops - Send Mail Example (Parent)
outputs: []
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dad4caa8-e9c4-4eb6-8c03-5c3f5ddf264b
      iscommand: false
      name: ""
      version: -1
    taskid: dad4caa8-e9c4-4eb6-8c03-5c3f5ddf264b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -240
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Mail
      value:
        complex:
          accessor: "0"
          root: You've got mail (soon).Answers
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: cfba89da-5ef7-4f0d-8c48-c65c49eedb07
      iscommand: false
      name: Set Mail
      script: Set
      type: regular
      version: -1
    taskid: cfba89da-5ef7-4f0d-8c48-c65c49eedb07
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 3
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      mailto:
        complex:
          root: Mail
          transformers:
          - args:
              delimiter:
                value:
                  simple: ','
            operator: split
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "Playbook takes the email to send to as input and sends a quick
        email message.  \n\nWhen used as a subplaybook you can add a loop to loop
        over each inputted list of emails to send one email to each person. "
      id: f0afad8e-03ca-40c5-8167-7f487c1c46f4
      iscommand: false
      name: XSOAR Engineer Training - For Each Loops - Send Mail (Sub-Playbook)
      playbookId: XSOAR Engineer Training - For Each Loops - Send Mail (Sub-Playbook)
      type: playbook
      version: -1
    taskid: f0afad8e-03ca-40c5-8167-7f487c1c46f4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: a5e9cbe3-fb9b-44f8-8cc0-1b6aad414cc6
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: a5e9cbe3-fb9b-44f8-8cc0-1b6aad414cc6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": -55
        }
      }
  "6":
    continueonerrortype: ""
    form:
      description: 'Please add the email addresses you want to send to in comma separated
        format '
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Emails
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: Email addresses in comma separated format (e.g test@example.com,test2@example.com)
        type: shortText
      sender: ""
      title: You've got mail (soon)
      totalanswers: 0
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Email Addresses
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Which emails to send.
      id: 493879c5-5efe-4dfc-8c65-6040def000a0
      iscommand: false
      name: Query User for Email Addresses
      type: collection
      version: -1
    taskid: 493879c5-5efe-4dfc-8c65-6040def000a0
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1cd14d58-f061-4d12-83e1-c5e254559528
      iscommand: false
      name: Loops (Note the Loop settings on the below Subplaybook)
      type: title
      version: -1
    taskid: 1cd14d58-f061-4d12-83e1-c5e254559528
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d7fd6f7d-9bf7-4fc5-801d-47d81a915097
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d7fd6f7d-9bf7-4fc5-801d-47d81a915097
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: "## XSOAR Engineer Training - For Each Loops - Send Mail Example (Parent)\n\nThis
          playbook demonstrates a for each loop with a sub-playbook to send each user
          an individual email. "
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 4d9b8b16-6767-48ee-87b6-1b1cfe01992c
      iscommand: false
      name: Print Playbook Overview
      script: Print
      type: regular
      version: -1
    taskid: 4d9b8b16-6767-48ee-87b6-1b1cfe01992c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 150
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 380,
        "x": 50,
        "y": -240
      }
    }
  }
