contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: df923d3a-4f95-4269-81c9-32476ff663ff
inputs: []
name: Telia MS Defender Incidents
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a8e778f7-4c0e-4eb5-8bd7-29314710579c
      iscommand: false
      name: ""
      version: -1
    taskid: a8e778f7-4c0e-4eb5-8bd7-29314710579c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 65
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              simple: incident.status
          operator: isEqualString
          right:
            value:
              simple: Closed
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 600
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ff8f9b5b-7aed-4af5-8b8c-31c4231d4db9
      iscommand: false
      name: Telia Link MS Defender Alerts to Incidents
      playbookId: 8b4dfd8f-1664-4a18-8361-b169860b1612
      type: playbook
      version: -1
    taskid: ff8f9b5b-7aed-4af5-8b8c-31c4231d4db9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 705,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: ${incident.microsoft365defenderdisplayname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 5f2dba91-0689-4aa9-8cf6-f9465dba55eb
      iscommand: true
      name: Set Incident Name
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 5f2dba91-0689-4aa9-8cf6-f9465dba55eb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 225
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Address
          root: IP
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      tags:
        simple: Defender
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of multiple indicators
      id: 29bdad20-b0f5-4663-8afb-c837ad0b21ad
      iscommand: true
      name: setIndicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: 29bdad20-b0f5-4663-8afb-c837ad0b21ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1275
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Data
          root: URL
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      tags:
        simple: Defender
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of multiple indicators
      id: 970141f7-6e8e-4dfe-8a09-2a9973c340b1
      iscommand: true
      name: setIndicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: 970141f7-6e8e-4dfe-8a09-2a9973c340b1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
      - "4"
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 7374c2f5-9a89-4c59-8144-395b2ed76511
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 7374c2f5-9a89-4c59-8144-395b2ed76511
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 400
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Name
          root: Domain
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      tags:
        simple: Defender
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of multiple indicators
      id: 2ce13d2b-2aff-496d-89cd-4c08b8f251ba
      iscommand: true
      name: setIndicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: 2ce13d2b-2aff-496d-89cd-4c08b8f251ba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 575
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      domain:
        complex:
          accessor: Name
          root: Domain
      qtype:
        simple: A,AAAA
      server:
        simple: 8.8.8.8
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns DNS details for a domain.
      id: 93f8e3cb-544c-48c8-84c4-149b57ed2cc0
      iscommand: false
      name: GetDomainDNSDetails
      script: GetDomainDNSDetails
      type: regular
      version: -1
    taskid: 93f8e3cb-544c-48c8-84c4-149b57ed2cc0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 925
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: adb7c28c-0764-45b9-83e2-bdbeedc48ad6
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: adb7c28c-0764-45b9-83e2-bdbeedc48ad6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1100
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Address
          root: IPv6
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      tags:
        simple: Defender
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of multiple indicators
      id: b9d1d6a6-17aa-4593-8a50-a3cf4edd910f
      iscommand: true
      name: setIndicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: b9d1d6a6-17aa-4593-8a50-a3cf4edd910f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1275
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Name
                root: Domain
          operator: isEmpty
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c2c4ab95-be9e-4ba1-8819-22bf3cc17976
      iscommand: false
      name: Check if Domain is empty
      type: condition
      version: -1
    taskid: c2c4ab95-be9e-4ba1-8819-22bf3cc17976
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 750
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1320,
        "width": 1035,
        "x": 50,
        "y": 50
      }
    }
  }
