contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This is a sub-playbook that simulates an AD Password Reset process,
  which can be used as a sub-playbook across a number of different playbooks simply
  by adding it in, and passing the proper inputs in. \n\nThis sub-playbook will output
  the new password, so it can be provided to the User, or maybe the users manager. "
id: XSOAR Engineer Training - AD Password Reset  (Sub-Playbook)
inputs:
- description: The samAccountName of the user to reset the password for.
  key: username
  playbookInputQuery: null
  required: true
  value: {}
name: XSOAR Engineer Training - AD Password Reset  (Sub-Playbook)
outputs:
- contextPath: NEW_PASSWORD
  description: The new password generated for the user.
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e9ba6ac0-33cf-4cc8-8cd0-15d104e65d67
      iscommand: false
      name: ""
      version: -1
    taskid: e9ba6ac0-33cf-4cc8-8cd0-15d104e65d67
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      password:
        complex:
          root: NEW_PASSWORD
      username:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: XSOAR Engineer Training
      description: Sets a new password for an Active Directory user.
      id: 3554e131-635b-4bab-8e9a-97ed8b80e7a9
      iscommand: true
      name: 'Reset User Password '
      script: XSOAR Engineer Training|||ad-set-new-password
      type: regular
      version: -1
    taskid: 3554e131-635b-4bab-8e9a-97ed8b80e7a9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "This function generates a password and allows various parameters
        to customize the properties of the password depending on the use case (e.g.
        password complexity requirements).  The default behavior is to generate a
        password of  *random length* including all four character classes (upper,
        lower, digits, symbols) with at least five and at most ten characters per
        class. \n\nThe min_* values all default to 0. This means that if the command
        is executed in this way:\n!GeneratePassword max_lcase=10\nIt is possible that
        a password of length zero could be generated. It is therefore recommended
        to always include a min_* parameter that matches. \n\nThe debug parameter
        will print certain properties of the command into the WarRoom for easy diagnostics."
      id: 848c8276-b335-4109-864d-782a7e2eb1ae
      iscommand: false
      name: Generate Password
      script: GeneratePassword
      type: regular
      version: -1
    taskid: 848c8276-b335-4109-864d-782a7e2eb1ae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4f51f8b4-a818-4c91-81b0-a6c950850986
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4f51f8b4-a818-4c91-81b0-a6c950850986
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: XSOAR Engineer Training
      description: Expires the password of an Active Directory user.
      id: 0de9b323-4126-43ea-865c-e28c72e3c2a1
      iscommand: true
      name: Expire Password to force change
      script: XSOAR Engineer Training|||ad-expire-password
      type: regular
      version: -1
    taskid: 0de9b323-4126-43ea-865c-e28c72e3c2a1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
