contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.0.0
    packID: XSOAR_Engineer_Training
    packName: XSOAR Engineer Training
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This playbook demonstrates how a playbook task loops over an array of
  data, and different ways to handle that.\n\nBy default when you pass an array into
  an integration command or an Automation script, it run the command for each item
  in the array.   \n\nThis behaviour can be changed by using the \"Is Array\" option
  on the argument, which tells XSOAR to expect an array in this field, and run once
  instead.\n\nThis playbook demonstrates this using 2 automations, one is IsIPinRanges,
  the other is CheckCIDRinList, which is a custom automation in this pack.  Both can
  be viewed from the Automations menu."
id: XSOAR Engineer Training - Loop on Array Data
inputs: []
name: XSOAR Engineer Training - Loop on Array Data
outputs: []
starttaskid: "0"
system: true
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6a0c24ae-c87e-4800-8329-2f868b3e5a07
      iscommand: false
      name: ""
      version: -1
    taskid: 6a0c24ae-c87e-4800-8329-2f868b3e5a07
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 767372e3-61fd-4268-89df-c541a04d0c15
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 767372e3-61fd-4268-89df-c541a04d0c15
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 9946392e-3ddf-497a-859a-6bdcc379e141
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 9946392e-3ddf-497a-859a-6bdcc379e141
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: true
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      value:
        simple: "## XSOAR Engineer Training - Loop on Array Data\n\nBy default when
          you pass an array into an integration command or an Automation script, it
          run the command for each item in the array.   \n\nThis behaviour can be
          changed by using the \"Is Array\" option on the argument, which tells XSOAR
          to expect an array in this field, and run once instead.\n\nThis playbook
          demonstrates this using 2 automations, one is IsIPinRanges, the other is
          CheckCIDRinList, which is a custom automation in this pack.  Both can be
          viewed from the Automations menu."
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 7af6571a-3423-486e-8d3f-deb1adb4de65
      iscommand: false
      name: Print Playbook Overview
      script: Print
      type: regular
      version: -1
    taskid: 7af6571a-3423-486e-8d3f-deb1adb4de65
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: IPArray
      value:
        simple: '["8.8.8.1","8.8.8.2","8.8.8.3","10.8.8.1","10.8.8.2"]'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Set a value in context under the key you entered.
      id: 191d691e-e3df-48ba-8d8a-a323b873cf49
      iscommand: false
      name: Set Array of IPs to Context
      script: Set
      type: regular
      version: -1
    taskid: 191d691e-e3df-48ba-8d8a-a323b873cf49
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      ip:
        complex:
          root: IPArray
      ipRanges:
        simple: ${lists.Internal IP Ranges}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns yes if the IP is in one of the ranges provided, returns
        no otherwise.
      id: f2701489-6023-4a87-8042-8e372c297dbc
      iscommand: false
      name: Is IP in Ranges
      script: IsIPInRanges
      type: regular
      version: -1
    taskid: f2701489-6023-4a87-8042-8e372c297dbc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      ips:
        complex:
          root: IPArray
      listname:
        simple: Internal IP Ranges
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines whether an IPv4 address is contained in one or more
        comma-delimited CIDR ranges.  You can pass in an array of IPs, and the name
        of the XSOAR list containing the comma separated list of CIDRs or /32 addresses.
      id: 1ff5266d-b98f-4990-82f9-5b120ddc3d70
      iscommand: false
      name: CheckIPsinCIDRList (uses Is Array)
      script: CheckIPsinCIDRList
      type: regular
      version: -1
    taskid: 1ff5266d-b98f-4990-82f9-5b120ddc3d70
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
