contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.7.2
    packID: RecordedFuture
    packName: Recorded Future Intelligence
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
id: Recorded Future Detailed Alert example
inputs:
- description: "A static playbook that generates the most recent vulnerability alerts
    with extended details about what these alerts contain.\n\nThe value can be switched
    out to credential or typosquat to get detailed alerts for typosquats and credential
    leaks respectively. "
  key: Vulnerability alerts
  playbookInputQuery: null
  required: false
  value:
    simple: vulnerability
name: Recorded Future Detailed Alert example
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 52ac4e72-803d-477d-809a-14c325268d50
      iscommand: false
      name: ""
      version: -1
    taskid: 52ac4e72-803d-477d-809a-14c325268d50
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 620,
          "y": 40
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      freetext:
        simple: ${inputs.Vulnerability alerts}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get details on alerts configured and generated by Recorded Future
        by alert rule ID and/or time range.
      id: 118a1986-86b5-4643-8826-9de059078383
      iscommand: true
      name: recordedfuture-alerts
      script: Recorded Future v2|||recordedfuture-alerts
      type: regular
      version: -1
    taskid: 118a1986-86b5-4643-8826-9de059078383
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 250
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${RecordedFuture.Alert.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Detailed alert example
      id: ef9c0bc1-0cc5-4375-8860-3b5401879d63
      iscommand: true
      name: recordedfuture-single-alert
      script: Recorded Future v2|||recordedfuture-single-alert
      type: regular
      version: -1
    taskid: ef9c0bc1-0cc5-4375-8860-3b5401879d63
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 440
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 495,
        "width": 450,
        "x": 620,
        "y": 40
      }
    }
  }
