contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.7.2
    packID: RecordedFuture
    packName: Recorded Future Intelligence
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Domain reputation using Recorded Future SOAR enrichment
id: Recorded Future Domain Reputation
inputs:
- description: The domain name to get reputation of.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Name
      root: Domain
name: Recorded Future Domain Reputation
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: Domain.Malicious.Vendor
  description: For malicious domains, the vendor that made the decision
  type: string
- contextPath: Domain.Malicious.Description
  description: For malicious domains, the reason that the vendor made the decision
  type: string
- contextPath: Domain.Name
  description: Domain name
  type: string
- contextPath: RecordedFuture.Domain.riskScore
  description: Recorded Future Domain Risk Score
  type: number
- contextPath: RecordedFuture.Domain.riskLevel
  description: Recorded Future Domain Risk Level
  type: string
- contextPath: RecordedFuture.Domain.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.Domain.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.Domain.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.Domain.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.Domain.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.Domain.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.Domain.name
  description: Domain name
  type: string
- contextPath: RecordedFuture.Domain.maxRules
  description: Maximum count of Recorded Future Domain Risk Rules
  type: number
- contextPath: RecordedFuture.Domain.ruleCount
  description: Number of triggered Recorded Future Domain Risk Rules
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 46eaf52b-f22e-4d99-8b97-f389db8f5d5c
      iscommand: false
      name: ""
      version: -1
    taskid: 46eaf52b-f22e-4d99-8b97-f389db8f5d5c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the playbook's input contains at least one domain
        name for which to get the reputation.
      id: 844d9fad-8cb7-4877-8d6e-cc55f81657d3
      iscommand: false
      name: Is there a domain to get reputation of?
      type: condition
      version: -1
    taskid: 844d9fad-8cb7-4877-8d6e-cc55f81657d3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a53e5ad6-3d5a-47fc-8afc-e4a1a66fe039
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a53e5ad6-3d5a-47fc-8afc-e4a1a66fe039
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future v2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: ef521fa4-102a-472b-8ed9-2e9afde09347
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: ef521fa4-102a-472b-8ed9-2e9afde09347
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a domain.
      id: f70a438e-3494-4fa6-859a-a304ff7e553f
      iscommand: true
      name: Get domain reputation from Recorded Future
      script: Recorded Future v2|||domain
      type: regular
      version: -1
    taskid: f70a438e-3494-4fa6-859a-a304ff7e553f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 560,
          "y": 690
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d402c8af-de3f-4ff0-8e3a-3bdfe2366d02
      iscommand: false
      name: Get reputation using Recorded Future API
      type: title
      version: -1
    taskid: d402c8af-de3f-4ff0-8e3a-3bdfe2366d02
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      recordedfutureriskrules:
        simple: ${RecordedFuture.Domain.rules}
      value:
        simple: ${inputs.Domain}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of an indicator
      id: 7843cabc-fd9a-4730-8427-5b2abdaebbe4
      iscommand: true
      name: setIndicator
      script: Builtin|||setIndicator
      type: regular
      version: -1
    taskid: 7843cabc-fd9a-4730-8427-5b2abdaebbe4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 560,
          "y": 850
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57,
      "26_24_#default#": 0.55,
      "26_28_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 895,
        "width": 890,
        "x": 50,
        "y": 50
      }
    }
  }
